package org.ihtsdo.termserver.scripting.pipeline.loinc;

import org.ihtsdo.termserver.scripting.domain.Concept;
import org.ihtsdo.termserver.scripting.pipeline.ContentPipeLineConstants;

public interface LoincScriptConstants extends ContentPipeLineConstants {

	Concept ORD_REFSET = new Concept("635111010000100", "LOINC Orderable Reference Set");
	Concept OBS_REFSET = new Concept("635121010000106", "LOINC Observable Reference Set");

	String LOINC_PART_TYPE_ADJUSTMENT = "ADJUSTMENT";
	String LOINC_PART_TYPE_CHALLENGE = "CHALLENGE";
	String LOINC_PART_TYPE_CLASS = "CLASS";
	String LOINC_PART_TYPE_COMPONENT = "COMPONENT";
	String LOINC_PART_TYPE_COUNT = "COUNT";
	String LOINC_PART_TYPE_DEVICE = "DEVICE";
	String LOINC_PART_TYPE_DIVISORS = "DIVISORS";
	String LOINC_PART_TYPE_METHOD = "METHOD";
	String LOINC_PART_TYPE_PROPERTY = "PROPERTY";
	String LOINC_PART_TYPE_SCALE = "SCALE";
	String LOINC_PART_TYPE_SUFFIX = "SUFFIX";
	String LOINC_PART_TYPE_SUPER_SYSTEM = "SUPER SYSTEM";
	String LOINC_PART_TYPE_SYSTEM = "SYSTEM";
	String LOINC_PART_TYPE_TIME = "TIME";
	String LOINC_PART_TYPE_TIME_MODIFIER = "TIME MODIFIER";


	String COMPONENT_PN = "COMPONENT_PN";
	String COMPONENTCORE_PN = "COMPONENTCORE_PN";
	String COMPSUBPART2_PN = "COMPSUBPART2_PN";
	String COMPSUBPART3_PN = "COMPSUBPART3_PN";
	String COMPSUBPART4_PN = "COMPSUBPART4_PN";
	String COMPNUM_PN = "COMPNUM_PN";
	String COMPDENOM_PN = "COMPDENOM_PN";
	String PROPERTY = "PROPERTYMIXEDCASE_PN";
	String COMPNUMSUFFIX_PN = "COMPNUMSUFFIX_PN";
	String SYSTEM_PN = "SYSTEM_PN";

	int FILE_IDX_LOINC_PARTS_MAP_BASE_FILE = 1;
	int FILE_IDX_LOINC_PARTS = 3;
	int FILE_IDX_LOINC_FULL = 4;
	int FILE_IDX_LOINC_DETAIL = 5;
	int FILE_IDX_PANELS = 6;

}
