package org.ihtsdo.termserver.scripting.pipeline.loinc;

import org.ihtsdo.termserver.scripting.domain.Concept;
import org.ihtsdo.termserver.scripting.pipeline.ContentPipeLineConstants;

public interface LoincScriptConstants extends ContentPipeLineConstants {

	Concept ORD_REFSET = new Concept("635111010000100", "LOINC Orderable Reference Set");
	Concept OBS_REFSET = new Concept("635121010000106", "LOINC Observable Reference Set");

	String LOINC_PART_TYPE_ADJUSTMENT = "ADJUSTMENT";
	String LOINC_PART_TYPE_CHALLENGE = "CHALLENGE";
	String LOINC_PART_TYPE_CLASS = "CLASS";
	String LOINC_PART_TYPE_COMPONENT = "COMPONENT";
	String LOINC_PART_TYPE_COUNT = "COUNT";
	String LOINC_PART_TYPE_DEVICE = "DEVICE";
	String LOINC_PART_TYPE_DIVISORS = "DIVISORS";
	String LOINC_PART_TYPE_METHOD = "METHOD";
	String LOINC_PART_TYPE_PROPERTY = "PROPERTY";
	String LOINC_PART_TYPE_SCALE = "SCALE";
	String LOINC_PART_TYPE_SUFFIX = "SUFFIX";
	String LOINC_PART_TYPE_SUPER_SYSTEM = "SUPER SYSTEM";
	String LOINC_PART_TYPE_SYSTEM = "SYSTEM";
	String LOINC_PART_TYPE_TIME = "TIME";
	String LOINC_PART_TYPE_TIME_MODIFIER = "TIME MODIFIER";


	String COMPONENT_PN = "COMPONENT_PN";
	String COMPONENTCORE_PN = "COMPONENTCORE_PN";
	String COMPSUBPART1_PN = "COMPSUBPART1_PN";
	String COMPSUBPART2_PN = "COMPSUBPART2_PN";
	String COMPSUBPART3_PN = "COMPSUBPART3_PN";
	String COMPSUBPART4_PN = "COMPSUBPART4_PN";
	String COMPNUM_PN = "COMPNUM_PN";
	String COMPDENOM_PN = "COMPDENOM_PN";
	String PROPERTY = "PROPERTYMIXEDCASE_PN";
	String COMPNUMSUFFIX_PN = "COMPNUMSUFFIX_PN";
	String SYSTEM_PN = "SYSTEM_PN";

	int FILE_IDX_LOINC_PARTS_MAP_BASE_FILE = 1;
	int FILE_IDX_LOINC_100 = 0;
	int FILE_IDX_LOINC_100_PRIMARY = 2;
	int FILE_IDX_LOINC_PARTS = 3;
	int FILE_IDX_LOINC_FULL = 4;
	int FILE_IDX_LOINC_DETAIL = 5;
	int FILE_IDX_PANELS = 6;

	int IDX_LOINC_NUM = 0;
	int IDX_COMPONENT = 1;
	int IDX_PROPERTY = 2;
	int IDX_TIME_ASPCT = 3;
	int IDX_SYSTEM = 4;
	int IDX_SCALE_TYP = 5;
	int IDX_METHOD_TYP = 6;
	int IDX_CLASS = 7;
	int IDX_VERSIONLASTCHANGED = 8;
	int IDX_CHNG_TYPE = 9;
	int IDX_DEFINITIONDESCRIPTION = 10;
	int IDX_STATUS = 11;
	int IDX_CONSUMER_NAME = 12;
	int IDX_CLASSTYPE = 13;
	int IDX_FORMULA = 14;
	int IDX_EXMPL_ANSWERS = 15;
	int IDX_SURVEY_QUEST_TEXT = 16;
	int IDX_SURVEY_QUEST_SRC = 17;
	int IDX_UNITSREQUIRED = 18;
	int IDX_RELATEDNAMES2 = 19;
	int IDX_SHORTNAME = 20;
	int IDX_ORDER_OBS = 21;
	int IDX_HL7_FIELD_SUBFIELD_ID = 22;
	int IDX_EXTERNAL_COPYRIGHT_NOTICE = 23;
	int IDX_EXAMPLE_UNITS = 24;
	int IDX_LONG_COMMON_NAME = 25;
	int IDX_EXAMPLE_UCUM_UNITS = 26;
	int IDX_STATUS_REASON = 27;
	int IDX_STATUS_TEXT = 28;
	int IDX_CHANGE_REASON_= 29;
	int IDX_COMMON_TEST_RANK = 30;
	int IDX_COMMON_ORDER_RANK = 31;
	int IDX_COMMON_SI_TEST_RANK = 32;
	int IDX_HL7_ATTACHMENT_STRUCTURE = 33;
	int IDX_EXTERNAL_COPYRIGHT_LINK = 34;
	int IDX_PANELTYPE = 35;
	int IDX_ASKATORDERENTRY = 36;
	int IDX_ASSOCIATEDOBSERVATIONS = 37;
	int IDX_VERSIONFIRSTRELEASED = 38;
	int IDX_VALIDHL7ATTACHMENTREQUEST = 39;
	int IDX_DISPLAYNAME = 40;
}
